blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: https://github.com/dinoki-ai/tweaks/security/policy
    about: Please report security issues privately using our security policy
  - name: Questions and support
    url: https://github.com/dinoki-ai/tweaks/blob/main/SUPPORT.md
    about: How to get help and ask questions
